### ISSUE TITLE
Segmented nuclei are split

### ISSUE THREAD

**Issue by josenimo** [HMS-IDAC/S3segmenter#19]
Dear @clarenceyapp,

I am having a minor issue that many nuclei are divided into halfs (see pictures). My sample dataset is from HeLa cell culture, will upload subsample. Is there any parameter that I am missing which can lead to this kind of output? Open to suggestions :) 

![split nuclei](https://user-images.githubusercontent.com/30318135/194576784-931862f2-450f-415b-a0f8-8c2d08001f18.png)

for whole MCMICRO folder:
https://filetransfer.mdc-berlin.de/?u=BQjgtnur&p=p488jD9e

Best,
Jose

**Comment by clarenceyapp** [comment]
Hi @josenimo 
Thanks for sending the files in. In the s3seg-opts, you can try increasing the `--logSigma` parameter since the resolution of your images are 4 times larger than the training data. Maybe try :  --logSigma 25 200 <<<< The first number controls the seeding of the watershed algorithm. The higher the number, the less over-splitting there will be but it can also cause cells now to clump together if the number is too high.

Clarence

**Comment by josenimo** [comment]
Hey @clarenceyapp 
I have played around with the --logSigma setting, and found what you suggest, I found that 30 200 to be a decent tradeoff, 40 220 was too much and started losing many nuclei. 

I am uploading the qc files in case you want to check the difference between them. 
https://filetransfer.mdc-berlin.de/?u=CvbnRJKv&p=cvJ2hUyb

Just wondering is there a faster way to run multiple intances of MCMICRO, while changing a single variable few times? Besides of course manually doing so? 

Thanks again,
Jose

**Comment by clarenceyapp** [comment]
Hi @josenimo 
Thanks for sending those qc files. Yes, I agree 30 200 appears to be the best set of parameters. There is still some oversplitting due to the nature of the watershed algorithm that is difficult to avoid. We are working to implement ''smarter'' methods that will reduce this problem. 

I will have to refer your question to @ArtemSokolov about whether it's possible to run MCMICRO multiple times each with different parameters ie. parameter tuning. Currently, I don't believe this is possible.

Clarence

**Comment by ArtemSokolov** [comment]
Unfortunately, rapid evaluation on a parameter grid is not straightforward. But I really like that idea, so I'll have to think about how to best allow users to do that.

**Comment by josenimo** [comment]
Hey @ArtemSokolov, thank you, MCMICRO has grown so many nice features! Amazing work!
