### ISSUE TITLE
Bug? The input image seems to have just one color 0.0.

### ISSUE THREAD

**Issue by josenimo** [HMS-IDAC/S3segmenter#9]
Dear developer team of S3segmenter,

I am Jose Nimo, a PhD student trying to apply MCMICRO to some images provided by our pathologist collaborator. For some reason the segmentation step with S3seg fails. The error saying that my image seems to have just one color 0.0. When I inspect the image manually (I will upload) it seems fine, Nuclei stain is the first image, also shown in the markers.csv file (also uploaded). I have compared the metadata between the example images provided by MCMICRO and the ones by my colaborator and they do seem quite different. However, they say that these images have worked with previous analyses without any issues. 

I thank you for the incredible software you have released, I am very excited to put it to use!
Best wishes,
Jose

Download link (https://filetransfer.mdc-berlin.de/?u=9GxV6H6t&p=ZmW9mQej)

**Comment by clarenceyapp** [comment]
Hi Jose, 
I was the original developer of S3segmenter. I tested your image but was unable to reproduce the problem (see screenshot below).
![image](https://user-images.githubusercontent.com/22457035/148804853-21d27013-c39e-4bb1-b5a7-1bdc93a6d4a7.png)

I ran MCMICRO from UnMICST till S3segmenter, which you can do too if your collaborator's image is pre-stitched already. Is it prestitched or were you given separated tiles?
Thanks.

Clarence

**Comment by clarenceyapp** [comment]
Hi Jose,
Further to my previous post, I was able to reproduce the problem by starting MCMICRO from `illumination`, which you don't need to do if you have a pre-stitched image already. Please place your collaborator's image in a new folder called `registration`. Then, specify `--start-at probability-maps` instead of `illumination`. This will skip illumination correction and stitching and registration.

There are some other notable parameters that you might want to adjust. If you are using UnMICST beforehand, you will need to set the `--downsample` parameter to about 0.25 since the image has 4 times higher resolution than the training data. If you are using channel 1 for your nuclei detection, it is actually quite dim. I found that `--channel 7` has more dynamic range and I used that instead. 

Next, for s3segmenter parameters, you should set the `--logSigma` parameter to about a suitable size, which is about 20 to 200 in your case. Finally, because I used channel 7, I set `--probMapChan 7` too. The screenshot I included earlier is the result of doing this with the segmentation outlines in red. It could still use abit more tweaking though to capture more nuclei.

**Comment by josenimo** [comment]
Hey Clarence, 
Thank you very much for your comments, you really helped me grasp how the pipeline works. However I have ran into another error trying to replicate your result. As you mentioned: I placed the same image in a folder called registration, and ran the following command:

` nextflow run labsyspharm/mcmicro --in MCMICRO_tests/MCMICRO_03 --start-at probability-maps --unmicst-opts '--channel 7 --scalingFactor 0.25' --s3seg-opts '--probMapChan 7 --logSigma 20 200'`

I obtained the following error message (see in txt file):
[20220111_bug_MCMICRO_06.txt](https://github.com/HMS-IDAC/S3segmenter/files/7847123/20220111_bug_MCMICRO_06.txt)

Thank you for your help!

**Comment by josenimo** [comment]
Thank you Clarence for your kind comments! You have helped me understand the pipeline much better!

**Comment by clarenceyapp** [comment]
Hi Jose, Actually, I used 20 to 150 for the logSigma parameter and 0.3 for the downSample parameter. You can try playing around with these parameters abit to get more cells. You are right that 20 to 200  gives that error message. It means that no cells were detected and we are working on making it give a more comprehensive message next time. 
Alternatively, since your images are quite small in size, you can also try combining the probability maps with your collaborator's image along the channel axis and analyze it in Cellprofiler. It is interactive and you can get immediate feedback when you change parameters. 

Clarence
